"""relacionando_cursos_e_disciplinas

Revision ID: e86d6eb564a6
Revises: 3aa3a204d952
Create Date: 2025-10-27 22:10:20.335056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86d6eb564a6'
down_revision: Union[str, Sequence[str], None] = '3aa3a204d952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_disciplines',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'discipline_id')
    )
    op.drop_constraint(op.f('courses_name_key'), 'courses', type_='unique')
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=True)
    op.drop_index(op.f('ix_disciplines_course_id'), table_name='disciplines')
    op.create_index(op.f('ix_disciplines_name'), 'disciplines', ['name'], unique=True)
    op.drop_constraint(op.f('disciplines_course_id_fkey'), 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('disciplines_course_id_fkey'), 'disciplines', 'courses', ['course_id'], ['id'])
    op.drop_index(op.f('ix_disciplines_name'), table_name='disciplines')
    op.create_index(op.f('ix_disciplines_course_id'), 'disciplines', ['course_id'], unique=False)
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.create_unique_constraint(op.f('courses_name_key'), 'courses', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_table('course_disciplines')
    # ### end Alembic commands ###
